export const members = [
  {
    name: "Kamile Pimentel",
    course: "Ciência da Computação",
    year: "2022/1",
    image: "/kamile.png",
  },
  {
    name: "Luana Hahn",
    course: "Ciência da Computação",
    year: "2021/1",
    image: "/luana.png",
  },
  {
    name: "Kathleen Hoff (Kathi)",
    course: "Ciência da Computação",
    year: "2020/2",
    image: "/kathleen.png",
  },
  {
    name: "Thais Marcelle (Marti)",
    course: "Engenharia da Computação",
    year: "2022/1",
    image: "/thais.png",
  },
  {
    name: "Luma Besserra",
    course: "Ciência da Computação",
    year: "2021/2",
    image: "/luma.png",
  },
  {
    name: "Milena Silva Braga",
    course: "Ciência da Computação",
    year: "2019/2",
    image: "/milena.png",
  },
  {
    name: "Ingrid Murielem",
    course: "Ciência da Computação",
    year: "2020/1",
    image: "/ingrid.png",
  },
  {
    name: "Julianne Emanuelle Martins",
    course: "Ciência da Computação",
    year: "2022/1",
    image: "/julianne.png",
  },
  {
    name: "Juliana Schmitt",
    course: "Ciência da Computação",
    year: "2020/2",
    image: "/juliana.png",
  },
  {
    name: "Maria Flávia Borrajo Tondo",
    course: "Mestrado",
    year: "2023/2",
    image: "/maria.png",
  },
  {
    name: "Joana Campos",
    course: "Ciência da Computação",
    year: "2021/1",
    image: "/joana.png",
  },
  {
    name: "Gisele Rotta",
    course: "Ciência da Computação",
    year: "2023/1",
    image: "/gisele.png",
  },
  {
    name: "Laura Grippa",
    course: "Ciência da Computação",
    year: "2015/1",
    image: "/laura_grippa.png",
  },
  {
    name: "Lisa Manami Adate",
    course: "Ciência da Computação",
    year: "2023/2",
    image: "/lisa.png",
  },
  {
    name: "Bruna Schmidt",
    course: "Engenharia da Computação",
    year: "2023/1",
    image: "/bruna.png",
  },
  {
    name: "Sofia Popsin Gomes",
    course: "Engenharia da Computação",
    year: "2019/2",
    image: "/sofia.png",
  },
  {
    name: "Elisa Cristini",
    course: "Ciência da Computação",
    year: "2023/2",
    image: "/elisa.png",
  },
  {
    name: "Jade Hatanaka",
    course: "Ciência da Computação",
    year: "2021/1",
    image: "/jade.png",
  },
  {
    name: "Leticia Santos Machado",
    course: "Ciência da Computação",
    year: "2020/1",
    image: "/leticia.png",
  },
  {
    name: "Isis Burmeister Pericolo",
    course: "Ciência da Computação",
    year: "2018/1",
    image: "/isis.png",
  },
  {
    name: "Mariana Kaori",
    course: "Engenharia da Computação",
    year: "2020/1",
    image: "/mariana.png",
  },
  {
    name: "Laura Keidann",
    course: "Ciência da Computação",
    year: "2020/1",
    image: "/laura_keidann.png",
  }
];