import type { Metadata } from "next";
import { Pixelify_Sans, VT323 } from "next/font/google";
import "./globals.css";

const pixelify_sans = Pixelify_Sans();

const vt323 = VT323({
  weight: "400"
});

export const metadata: Metadata = {
  title: "Program.Ada - Mulheres da Computação",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="scroll-smooth">
      <body
        className={`${pixelify_sans.className} ${vt323.className} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
